### ISSUE TITLE
No Video Displayed

### ISSUE THREAD

**Issue by williamschey** [adamrumbold/SBS.bundle#2] opened 2012-05-11 08:36 UTC
Hey, thanks for the plugin, very cool. But it no longer shows video, I can hear the audio for the video but no picture.

Any ideas?

**Comment by adamrumbold** [comment] 2012-05-11 08:57
Hi.

I'm aware of it - but unfortunately haven't been able to work out what changed, or what the issue is.  Other flv websites are OK, and the URLs it's adding to play look fine.  Have tried a few things but no luck - if I get a chance I'll have more of a play with it this weekend - as it frustrates me too.

cheers

Adam.

**Comment by williamschey** [comment] 2012-05-11 09:03
Thanks Adam, you rock.

**Comment by adamrumbold** [comment] 2012-08-07 09:05
issue now resolved with latest commit - flash player container had a changed URL.  closing issue.

**Closed as completed by adamrumbold** 2012-08-07 09:05 UTC
